version: '3.9'

services:
 
  food-db:
    container_name: food-db
    image: mysql:5.7.22
    restart: always
    ports:
      - "3308:3308"
    networks:
      - lcmartins-network
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: food
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -P 3310 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      timeout: 3s
      retries: 5
    expose:
      - 3308

  food-service:
    depends_on:
      food-db:
        condition: service_healthy
    image: lcmartins/food-service
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8089"
    networks:
      - lcmartins-network
    environment:
      PORT: 8089
      SPRING.DATASOURCE.URL: jdbc:mysql://food-db:3308/food?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING.DATASOURCE.DRIVER.CLASS.NAME: com.mysql.cj.jdbc.Driver
      SPRING.USERNAME: docker
      SPRING.PASSWORD: admin123

networks:
  lcmartins-network:
    driver: bridge