version: '3.9'

services:
 
  food-db:
    container_name: food-db
    image: mysql:5.7.22
    restart: always
    ports:
      - "3308:3308"
    networks:
      - lcmartins-network
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: food
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: [ "CMD-SHELL", "mysql -h localhost -P 3310 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      timeout: 3s
      retries: 5
    expose:
      - 3308

  food-service:
    depends_on:
      food-db:
        condition: service_healthy
    image: lcmartins/food-service
    restart: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8089"
    networks:
      - lcmartins-network
    environment:
      PORT: 8089
      SPRING.DATASOURCE.URL: jdbc:mysql://food-db:3308/food?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      SPRING.DATASOURCE.DRIVER.CLASS.NAME: com.mysql.cj.jdbc.Driver
      SPRING.USERNAME: docker
      SPRING.PASSWORD: admin123

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - lcmartins-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    networks:
      - lcmartins-network

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_CONNECT_CLUSTER: http://app-connect:8083
      PORT: 9021
    networks:
      - lcmartins-network
networks:
  lcmartins-network:
    driver: bridge