spring:

  application:
    name: food

  #  spring.datasource.url=jdbc:h2:mem:testdb
  #  spring.datasource.driverClassName=org.h2.Driver
  #  spring.datasource.username=sa
  #  spring.datasource.password=password
  #  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:food
    driver-class-name: org.h2.Driver
    username: sa
    password: admin123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console.enabled: true

#  datasource:
#    url: "jdbc:mysql://${DB_HOST:localhost}:3306/food?createDatabaseIfNotExist=true&serverTimezone=UTC"
#    username: root
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#


#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#
#



  jackson:
    property-naming-strategy: SNAKE_CASE
