server:
  port: ${PORT:8081}

spring:

  application:
    name: food

  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:3308/food?createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  h2:
    console.enabled: true

#  datasource:
#    url: "jdbc:mysql://${DB_HOST:localhost}:3306/food?createDatabaseIfNotExist=true&serverTimezone=UTC"
#    username: root
#    password:
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#


#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#
#


  jackson:
    property-naming-strategy: SNAKE_CASE
